---
title: "Botulinum"
author: "Kellie Ottoboni"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## Vignette Info

summary of the book section


```{r loadbotulinum}
library(permuter)
data(botulinum)
```

## First Analysis

```{r firstanalysis}
n = length(unique(botulinum[,1]))
p = dim(botulinum)[2]-4
paz = ifelse(botulinum[,4]=='botox',1,2)[1:20]
Time = botulinum$Time+1


botulinum=botulinum[,-c(1:4)]

D=array(0,dim=c(n,p,4))

for(t in 1:4){
D[,,t]=as.matrix(botulinum[Time==t,])
}

### differences Tj-T0

for(t in 2:4){
D[,,t] = D[,,t]-D[,,1]
}

D = D[,,-1]


####Analysis is done variable-by-variable since they have different sizes of missing botulinum 

B=100
T<-array(0,dim=c((B+1),p))

alternative = c(rep(-1,19),rep(1,5))  		

for(j in 1:p){
for(t in 1:3){

O = ifelse(is.na(D[,j,t])==TRUE,0,1)
y = ifelse(is.na(D[,j,t])==TRUE,0,D[,j,t])
nu = table(O,paz)
if(dim(nu)[1]>1){nu=nu[2,]}

T[1,j] = T[1,j] + sum(y[paz==1])*sqrt(nu[2]/nu[1])/nu[1]-sum(y[paz==2])*sqrt(nu[2]/nu[1])/nu[2]

}
}



for(bb in 2:(B+1)){


D.star = D[sample(1:n),,]
for(j in 1:p){
for(t in 1:3){

O = ifelse(is.na(D.star[,j,t])==TRUE,0,1)
y = ifelse(is.na(D.star[,j,t])==TRUE,0,D.star[,j,t])
nu = table(O,paz)
if(dim(nu)[1]>1){nu=nu[2,]}

T[bb,j] = T[bb,j] + sum(y[paz==1])*sqrt(nu[2]/nu[1])/nu[1]-sum(y[paz==2])*sqrt(nu[2]/nu[1])/nu[2]

}
}
}## end bb


for(j in 1:p){  T[,j]=T[,j]*alternative[j]  }

source("../R/t2p.r")
P=t2p(T) 

res =  data.frame(colnames(botulinum),P[1,]);
colnames(res) = c("Variable","Raw p-values")
res


p.adj = FWE.minP(P)
p.adj = data.frame(res[,1],p.adj)
colnames(p.adj) = colnames(res)
p.adj
```

## Second Analysis

```{r secondanalysis}
B=100
T<-array(0,dim=c((B+1),p))


D=array(0,dim=c(n,p,4))

for(t in 1:4){
D[,,t]=as.matrix(botulinum[Time==t,])
}

### differences Tj-T0

for(t in 2:4){
D[,,t] = D[,,t]-D[,,(t-1)]
}

D = D[,,-1]



DB=D[paz==1,,] ; n = dim(DB)[1]


for(j in 1:p){

Y = DB[,j,]
O = apply(Y,2,function(x){ifelse(is.na(x),0,1)})
Y = ifelse(is.na(DB[,j,]),0,DB[,j,])

nu = apply(O,2,sum)
S = apply(Y,2,sum)

for(t in 1:3){

T[1,j] = T[1,j] + 
(S[t]*sqrt(sum(nu[-t])/nu[t])-(sum(S)-S[t])*sqrt(sum(nu[-t])/nu[t]))^2

}
} #end p


for(bb in 2:(B+1)){


D.star = apply(DB,c(1,2),sample)
D.star=aperm(D.star,c(2,3,1))




for(j in 1:p){

Y = D.star[,j,]
O = apply(Y,2,function(x){ifelse(is.na(x),0,1)})
Y = ifelse(is.na(D.star[,j,]),0,D.star[,j,])

nu = apply(O,2,sum)
S = apply(Y,2,sum)

for(t in 1:3){

T[bb,j] = T[bb,j] + 
(S[t]*sqrt(sum(nu[-t])/nu[t])-(sum(S)-S[t])*sqrt(sum(nu[-t])/nu[t]))^2

}
} #end p

}


P=t2p(T)

P[1,]

```