---
title: "Kenya Data: A Case Study in Population Genetics"
author: "Kellie Ottoboni"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


## Vignette Info

This example comes from the textbook section 6.9.3 (p 321).

```{r kenya}
library(permuter)
data(kenya)
B <- 10000
```

```{r setup}
### NEW
o1 <- order(kenya[,2], decreasing = TRUE)
o2 <- order(kenya[,3], decreasing = TRUE)

f1 <- kenya[o1, 2]
f2 <- kenya[o2, 3]
f <- cbind(f1, f2)
f <- f[f1 > 0, ]
k <- seq_len(nrow(f))

y1 <- rep(k, f[ ,1])
y2 <- rep(k, f[, 2])
n1 <- length(y1)
n2 <- length(y2)
y <- c(y1, y2)

group <- rep(c(1, 2), c(n1, n2))

### OLD
X1 <- kenya[, 2]
X2 <- kenya[, 3]
K <- dim(kenya)[1]

o1 <- order(X1, decreasing = TRUE)
o2 <- order(X2, decreasing = TRUE)

C1 <- X1[o1]
C2 <- X2[o2]
C <- cbind(C1, C2)
C <- C[C1 > 0, ]

k <- seq(1, dim(C)[1])

Y1 <- rep(k, C[, 1])
Y2 <- rep(k, C[, 2])
n1 <- length(Y1)
n2 <- length(Y2)
Y <- c(Y1, Y2)

G <- rep(c(1, 2), c(n1, n2))
```

We'll use Gini index, Shannon's entropy index, and the Rényi index to measure heterogeneity.

```{r permutation}
gini <- function(f1, f2) {sum((f1/n1)^2 - (f2/n2)^2)}
shannon <- function(f1, f2) {
  logf1 <- rep(0, length(f1))
  logf1[f1 != 0] <- log(f1[f1 != 0]/n1)
  logf2 <- rep(0, length(f2))
  logf2[f2 != 0] <- log(f2[f2 != 0]/n2)
  sum((f1/n1)*logf1 - (f2/n2)*logf2)
}
renyi <- function(f1, f2) {log(max(f1/n1)) - log(max(f2/n2))}

observed <- c(gini(f[,1], f[,2]), shannon(f[,1], f[,2]), renyi(f[,1], f[,2]))

distr <- matrix(0, nrow = B, ncol = 3)
for(bb in seq_len(B)){
  y.star <- sample(y)
  c.star <- table(y.star, group)
  distr[bb, 1] <- gini(c.star[,1], c.star[,2])
  distr[bb, 2] <- shannon(c.star[,1], c.star[,2])
  distr[bb, 3] <- renyi(c.star[,1], c.star[,2])
}


## OLD

T.G <- array(0, dim = c((B + 1), 1))
T.S <- array(0, dim = c((B + 1), 1))
T.R <- array(0, dim = c((B + 1), 1))

T.G[1] <- sum((C[, 1]/n1)^2 - (C[, 2]/n2)^2)
T.S[1] <- sum((C[, 1]/n1) * ifelse(C[, 1] == 0, 0, log(C[, 1]/n1)) - (C[, 2]/n2) * 
    ifelse(C[, 2] == 0, 0, log(C[, 2]/n2)))
T.R[1] <- log(max(C[, 1]/n1)) - log(max(C[, 2]/n2))


for (bb in 2:(B + 1)) {
    Y.star <- sample(Y)
    C.star <- table(Y.star, G)
    T.G[bb] <- sum((C.star[, 1]/n1)^2 - (C.star[, 2]/n2)^2)
    T.S[bb] <- sum((C.star[, 1]/n1) * ifelse(C.star[, 1] == 0, 0, log(C.star[, 1]/n1)) - 
        (C.star[, 2]/n2) * ifelse(C.star[, 2] == 0, 0, log(C.star[, 2]/n2)))
    T.R[bb] <- log(max(C.star[, 1]/n1)) - log(max(C.star[, 2]/n2))
}



 


```

Set Het(1) > Het(2), then $1-\sum_k p_{(k)1}^2 > 1-\sum_k p_{(k)2}^2$. We care about when $\sum_k p_{(k)1}^2 - p_{(k)2}^2< 0$; small is significant.

```{r kenya2}
pvalues <- sapply(1:3, function(i) t2p(observed[i], distr[,i], alternative = "less"))
pvalues

### OLD
p.G <- t2p_old(-T.G)[1]
p.S <- t2p_old(-T.S)[1]
p.R <- t2p_old(-T.R)[1]

res <- c(p.G, p.S, p.R)
res



 


```


