# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

permute_cpp <- function(a) {
    .Call('permuter_permute_cpp', PACKAGE = 'permuter', a)
}

